[package]
name = "splitter"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mainlib = { path = "../mainlib" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
