[package]
name = "mainlib"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1.0"
sha2 = "0.10"
pbkdf2 = "0.12"
hmac = "0.12"
rand = "0.8"
